version: '3'

services:

  nginx:
    image: nginx:v1
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    env_file:
      - .env
    depends_on:
      - wordpress   # wait for wp to finish then build
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - ./requirements/nginx/conf/:/etc/nginx/http.d/
      - wp-volume:/var/www
      # - ./requirements/nginx/tools:/etc/nginx/ssl/
      # - /home/${USER}/simple_docker_nginx_html/public/html:/var/www/
    restart: always
    # restart: unless-stopped # not allowed in subj

  mariadb:
    image: mariadb:v1
    build:
      context: .
      dockerfile: requirements/mariadb/Dockerfile
      # not sure about this args part below
      args:
        DB_ROOT: ${DB_ROOT}
        DB_USER: ${DB_USER}
        DB_NAME: ${DB_NAME}
        DB_PASS: ${DB_PASS}
        # These env vars are not present in the image
        # therefore they can only be passed here
        # But for ENV vars which can be found in the env section
        # they are already inside the service
    container_name: mariadb
    env_file:
      - .env
    networks:
      - inception
    ports:
      - "3306:3306"
        #volumes:
        #- db-volume:/var/lib/mysql
    restart: always

  wordpress:
    image: wordpress:v1
    build:
      context: .
      dockerfile: requirements/wordpress/Dockerfile
      args:
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASS: ${DB_PASS}
    container_name: wordpress
    env_file:
      - .env
    networks:
      - inception
    depends_on:
      - mariadb
    restart: always
    volumes:
      - wp-volume:/var/www/

volumes:
  wp-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/mariadb

networks:
  inception:
    driver: bridge
